# Generated by Django 5.1.2 on 2024-11-03 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodinventory',
            name='last_updated',
        ),
    ]
