# Generated by Django 5.1.2 on 2024-11-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_management', '0002_remove_bloodinventory_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodinventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
