# Generated by Django 5.1.2 on 2024-11-03 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_management', '0003_bloodinventory_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='last_donation_date',
        ),
    ]
