# Generated by Django 5.1.2 on 2024-11-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_management', '0005_remove_hospital_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
