# Generated by Django 5.1.2 on 2024-11-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_management', '0006_hospital_name_alter_hospital_hospital_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
